/* Enum for languages supported by LeetHub. */
const languages = {
  Python: '.py',
  Python3: '.py',
  'Python 3': '.py',
  'Pypy 2': '.py',
  'Pypy 3': '.py',
  'C++': '.cpp',
  'C++14': '.cpp',
  C: '.c',
  Java: '.java',
  'Java 7': '.java',
  'Java 8': '.java',
  'Java 15': '.java',
  'C#': '.cs',
  'Objective-C': '.m',
  Clojure: '.clj',
  JavaScript: '.js',
  Javascript: '.js',
  'JavaScript (Node.js)': '.js',
  Ruby: '.rb',
  Swift: '.swift',
  Go: '.go',
  Kotlin: '.kt',
  Scala: '.scala',
  Rust: '.rs',
  PHP: '.php',
  TypeScript: '.ts',
  Erlang: '.erl',
  Haskell: 'hs',
  Lua: 'lua',
  Perl: '.pl',
  MySQL: '.sql',
  'MS SQL Server': '.sql',
  Oracle: '.sql',
};

export { languages as default };
